### PR TITLE
Report errors for duplicate BibTeX entry keys

### PR DESCRIPTION
**Pull request by pfoerster**

### CODE REVIEW

**Comment by clason** [comment]
Nice! Do duplicate labels next 🙏  :)

**Comment by clason** [comment]
I just tested this (sorry for not doing so earlier!) and noticed a small nit: If you have duplicate keys, it will only report the error on one of them (the first one in the file?) If it's not hard to implement, it would be even more useful if it marked _all_ of them, so you can check them easily and see if it's a duplicate entry or an accidental ambiguity (say, two different papers that happen to have the same authors and year).

**Comment by pfoerster** [comment]
> If you have duplicate keys, it will only report the error on one of them (the first one in the file?)

Yes, that's intentional. The `Diagnostic` should have the `relatedInformation` field populated with the additional occurences of the duplicate key. Maybe, Neovim is not showing it. Here is, how it looks like in VSCode:

image

**Comment by clason** [comment]
Ah, I see. As far as I know, Neovim is indeed not doing anything with that field. It would be nice to be able to annotate the duplicate information in the file itself, to be honest. (I also feel that this is a bit unintuitive, since in your example, the actual error is actually on lines 3 _and_ 5, not on line 1?)

**Comment by pfoerster** [comment]
Maybe, it's easier to report one error for each entry and then link the duplicates via `relatedInformation` (and do the same thing for labels).

**Comment by clason** [comment]
I feel that would be the best approach. But it's not a deal-breaker either way! Being able to see _any_ error before trying to compile a huge file (and trashing your aux file in the process) is a huge quality of life gain :)

**Comment by pfoerster** [comment]
@clason I have created a new PR: https://github.com/latex-lsp/texlab/pull/908  🚀

**Pull request merged**
