### PR TITLE
Do not try to match the full key in completion

### LINKED ISSUE #510: Pre-filtered completion result failing on lines with `}`
I have finally managed to find a minimal reproducing example for something that has been bugging me for a long while: Completing `\cite` and `\ref` arguments fails if a) you type to filter the candidates and b) the parser finds a `}` somewhere near.

The following minimal example reproduces this on Neovim:

1. save the following as `texlab.lua`:
<details><summary>config file </summary>

```lua
local minimal_path = vim.fn.stdpath 'cache' .. '/test-minimal-config/site'

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd('set packpath=' .. minimal_path)

_G.load_config = function()
  vim.o.completeopt = 'noinsert,menuone,noselect'
  vim.o.omnifunc = 'v:lua.vim.lsp.omnifunc'
  require('lspconfig').texlab.setup {
    cmd = { vim.fn.stdpath 'data' .. '/lspconfig/texlab' }, -- not needed if texlab is on $PATH
  }
  vim.cmd [[ LspStart ]]
end

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = minimal_path .. '/pack',
      compile_path = minimal_path .. '/pack/_loader/start/_load/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end

local install_path = minimal_path .. '/pack/packer/start/packer.nvim'
if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', '--depth=1', 'git://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config() ]]
```

(Note that depending on where `texlab` is installed, you may need to adapt the `cmd` string; you can omit the line if `texlab` is on the `$PATH`.)

</details>

2. save the following as `test.tex`:

```tex
\documentclass{article}

\begin{document}

\begin{equation}\label{eq:foo}
    1+1=2
\end{equation}

Equation \eqref{eq is a \emph{useful} identity.

\end{document}
```

3. run `nvim --clean -u texlab.lua test.tex`

4. put the cursor after `{eq` and press `<c-x><c-o>` (control-x, followed by control-o)

This should offer `eq:foo` as completion candidate, but nothing happens. If I either
1. remove `eq` and put the cursor after `{`, or
2. remove the rest of the line (in particular the `\emph{useful}`!),

completion works as expected. (On the other hand, the `}` does not have to be on the same line; it can be on a line further down.)

I suspect that the parser is too "greedy" and considers everything to the next closing brace as the prefilter text, instead of only to (e.g.) the first whitespace character.

### PR DESCRIPTION
**Pull request by pfoerster**
Instead only match the key up to the cursor position.

Fixes #510.

### CODE REVIEW

**Comment by clason** [comment]
Yes, that seems to work nicely!

One thing I'm not quite clear on: If I modify the example in the issue to remove the space, for example
```tex
Equation |is a...
```
and then type `\eqref{` (so the text is `\eqref{|is`) I get _no_ completion candidates. If you only consider the text up to the cursor, shouldn't this still work?

Also, for really long lines (I know...), I see a definite input lag when filtering the completion candidates.

Neither is a deal-breaker; I just wanted to mention it.

**Comment by pfoerster** [comment]
> Also, for really long lines (I know...), I see a definite input lag when filtering the completion candidates.

017009f might help in this case. It prevents using the whole line as a pattern for the completion.

> and then type \eqref{ (so the text is \eqref{|is, where | is the cursor) I get no completion candidates. If you only consider the text up to the cursor, shouldn't this still work?

That was basically an off-by-one error. 4e1b5ff should fix it.

**Comment by clason** [comment]
> [017009f](https://github.com/latex-lsp/texlab/commit/017009f291bb12ace8d55c50642d5cd6085adf96) might help in this case. It prevents using the whole line as a pattern for the completion.

I'm actually not sure about that one -- now if I type a long key (unfortunately I have such long keys...), I suddenly get zero completions; that feels kinda weird... I'd take completeness over performance in this case. Alternative would be to up it to something like 20 or 30? Or make it configurable (not sure that'd be worth the complexity, though)?

> That was basically an off-by-one error. [4e1b5ff](https://github.com/latex-lsp/texlab/commit/4e1b5ffe1017c86b7cd6b753c068d3885b859b4d) should fix it.

😆 

Yep, looks good!

**Comment by pfoerster** [comment]
> Alternative would be to up it to something like 20 or 30?

I have a weird feeling that tells me that there is someone out there who uses a key with > 30 words 🤣 .

> Or make it configurable (not sure that'd be worth the complexity, though)?

I don't think another setting should be introduced for this one so I agree with favoring correctness over performance.

**Comment by clason** [comment]
> I have a weird feeling that tells me that there is someone out there who uses a key with > 30 words 🤣 .

Yeah, people writing TeX are a weird bunch ;) And agreed on no new setting. 

Thanks! Might be worth a point release?

**Comment by pfoerster** [comment]
> Might be worth a point release?

Yeah, I thought so too 👍 .

**Pull request merged**
