### PR TITLE
Parse verbatim blocks correctly

### LINKED ISSUE #490: Do not try to parse embedded (`asy`) code as TeX
The texlab parser seems to try to parse embedded `asy` code as TeX, with the expected results:
```tex
\begin{asy}
    for(int i=0; i<m; ++i){
        real x=getx(i);
        if(i%3==0){
            draw((x, 0)--(x, 0.332));
        }else if(i%3==1){
            draw((x, 0.333)--(x, 0.665));
        }else{
            draw((x, 0.665)--(x, 1));
        }
    }
\end{asy}
```
The problem here is the `i%3` -- the `%` is seen as a comment marker, even though `asy` is basically C code, so comments are marked with `//`.

I believe the best option is to just stop parsing known code environments (as `verbatim` already is?)

Off the top of my head, these would be
* `asy`
* `asydef`
* `luacode` (for lualatex)
* `minted`
* ...?

### PR DESCRIPTION
**Pull request by pfoerster**
This PR updates the current LaTeX lexer to handle verbatim environments like `\begin{verbatim}` correctly by not trying to parse the content as LaTeX code.

Fixes #490.

### CODE REVIEW

**Comment by pfoerster** [comment]
@clason Can you have a look at this? 

It does not use `tree-sitter` and I don't think replacing the parser is the way to go. The performance regressions with `tree-sitter` are just too high and replacing the parser is basically an entire rewrite of every LSP request. This PR is kind of a "quick and dirty fix" (I have some ideas for later refactorings though) but it should work just fine.

**Comment by clason** [comment]
Thank you! That seems to work on simple files, but crashes on my big "stress test project" with
```
[ERROR][2022-04-03 11:53:14] .../vim/lsp/rpc.lua:420	"rpc"	"/Users/clason/.local/share/nvim/lspconfig/texlab"	"stderr"	"thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/syntax/latex/parser.rs:156:18\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by pfoerster** [comment]
> Thank you! That seems to work on simple files, but crashes on my big "stress test project" with

Ah thanks. This panic comes from the LaTeX parser. Does your document contain a `\fi` somewhere? If yes, then I have a fix :)

**Comment by clason** [comment]
It does :) That fixed it, thank you! And the parsing error is gone, too!

**Comment by clason** [comment]
(And I was under the misimpression that you already switched to the tree-sitter parser, at least partly. If this is not the case, this fix is obviously better!)

**Comment by pfoerster** [comment]
> It does :) That fixed it, thank you! And the parsing error in the asy environment is gone, too!

Nice 👍 .

> (And I was under the misimpression that you already switched to the tree-sitter parser, at least partly. If this is not the case, this fix is obviously better!)

I think switching to the `tree-sitter` parser is not worth the effort at the moment. There is just too much code that needs to be updated to make the complete switch and achieving good performance is more difficult (traversing the tree is slower than a full parser with a non-incremental parser and traversing the tree incrementally creates a whole new set of other problems).

**Comment by clason** [comment]
> I think switching to the `tree-sitter` parser is not worth the effort at the moment. There is just too much code that needs to be updated to make the complete switch and achieving good performance is more difficult (traversing the tree is slower than a full parser with a non-incremental parser and traversing the tree incrementally creates a whole new set of other problems).

Yes, that makes a lot of sense. No need to switch if the current parser works (well)!

**Pull request merged**
